# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vla_service_pb2 as vla__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vla_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VLAServiceStub(object):
    """VLA inference service with unary, bidirectional streaming, and server streaming
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/vla.VLAService/Infer',
                request_serializer=vla__service__pb2.InferRequest.SerializeToString,
                response_deserializer=vla__service__pb2.InferResponse.FromString,
                _registered_method=True)
        self.InferStream = channel.stream_stream(
                '/vla.VLAService/InferStream',
                request_serializer=vla__service__pb2.InferRequest.SerializeToString,
                response_deserializer=vla__service__pb2.InferResponse.FromString,
                _registered_method=True)
        self.StatusStream = channel.unary_stream(
                '/vla.VLAService/StatusStream',
                request_serializer=vla__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=vla__service__pb2.ServerStatus.FromString,
                _registered_method=True)
        self.GetCameraConfig = channel.unary_unary(
                '/vla.VLAService/GetCameraConfig',
                request_serializer=vla__service__pb2.CameraConfigRequest.SerializeToString,
                response_deserializer=vla__service__pb2.CameraConfig.FromString,
                _registered_method=True)
        self.TensorBatchInfer = channel.unary_unary(
                '/vla.VLAService/TensorBatchInfer',
                request_serializer=vla__service__pb2.TensorBatchInferRequest.SerializeToString,
                response_deserializer=vla__service__pb2.TensorBatchInferResponse.FromString,
                _registered_method=True)


class VLAServiceServicer(object):
    """VLA inference service with unary, bidirectional streaming, and server streaming
    """

    def Infer(self, request, context):
        """Unary RPC: single request-response (compatible with original HTTP mode)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferStream(self, request_iterator, context):
        """Bidirectional streaming: client sends observation frames, server returns actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatusStream(self, request, context):
        """Server streaming: server pushes periodic status updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCameraConfig(self, request, context):
        """Unary RPC: query server's expected camera configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TensorBatchInfer(self, request, context):
        """Unary RPC: tensor-batch inference for preprocessed model inputs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VLAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=vla__service__pb2.InferRequest.FromString,
                    response_serializer=vla__service__pb2.InferResponse.SerializeToString,
            ),
            'InferStream': grpc.stream_stream_rpc_method_handler(
                    servicer.InferStream,
                    request_deserializer=vla__service__pb2.InferRequest.FromString,
                    response_serializer=vla__service__pb2.InferResponse.SerializeToString,
            ),
            'StatusStream': grpc.unary_stream_rpc_method_handler(
                    servicer.StatusStream,
                    request_deserializer=vla__service__pb2.StatusRequest.FromString,
                    response_serializer=vla__service__pb2.ServerStatus.SerializeToString,
            ),
            'GetCameraConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCameraConfig,
                    request_deserializer=vla__service__pb2.CameraConfigRequest.FromString,
                    response_serializer=vla__service__pb2.CameraConfig.SerializeToString,
            ),
            'TensorBatchInfer': grpc.unary_unary_rpc_method_handler(
                    servicer.TensorBatchInfer,
                    request_deserializer=vla__service__pb2.TensorBatchInferRequest.FromString,
                    response_serializer=vla__service__pb2.TensorBatchInferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vla.VLAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vla.VLAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VLAService(object):
    """VLA inference service with unary, bidirectional streaming, and server streaming
    """

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VLAService/Infer',
            vla__service__pb2.InferRequest.SerializeToString,
            vla__service__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vla.VLAService/InferStream',
            vla__service__pb2.InferRequest.SerializeToString,
            vla__service__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatusStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vla.VLAService/StatusStream',
            vla__service__pb2.StatusRequest.SerializeToString,
            vla__service__pb2.ServerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCameraConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VLAService/GetCameraConfig',
            vla__service__pb2.CameraConfigRequest.SerializeToString,
            vla__service__pb2.CameraConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TensorBatchInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vla.VLAService/TensorBatchInfer',
            vla__service__pb2.TensorBatchInferRequest.SerializeToString,
            vla__service__pb2.TensorBatchInferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
